services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: duolingo_root
      MYSQL_DATABASE: duolingo_db
      MYSQL_USER: duolingo_user
      MYSQL_PASSWORD: duolingo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - duolingo_network
  
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: duolingo_user
      POSTGRES_PASSWORD: duolingo_password
      POSTGRES_DB: duolingo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - duolingo_network

networks:
  duolingo_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local