from .Achievement import router as Achievement_router
from .Boosters import router as Boosters_router
from .Challenges import router as Challenges_router
from .ChallengesAchievement import router as ChallengesAchievement_router
from .ChallengesBoosters import router as ChallengesBoosters_router
from .Course import router as Course_router
from .CourseAchievement import router as CourseAchievement_router
from .Division import router as Division_router 
from .Lesson import router as Lesson_router
from .LessonBoosters import router as LessonBoosters_router
from .Progress import router as Progress_router
from .Question import router as Question_router
from .Section import router as Section_router
from .Stage import router as Stage_router
from .UserAchievement import router as UserAchievement_router
from .UserBoosters import router as UserBoosters_router
from .UserCourse import router as UserCourse_router
from .UserQuestion import router as UserQuestion_router